name: ML CI Test & Lint
on: [push,pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current code repo
        uses: actions/checkout@v4
      
      - name: setup python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: installing dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v

      - name: Lint the code
        run: flake8 src/ tests/