name: ML CI Test & Lint
on:
  push:
  pull_request:
    
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: pulling repo code into workflow environment
        uses: actions/checkout@v4
      
      - name: setup python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: installing dependencies
        working-directory: ci-pipeline-ml-model
        run: |
          pip install -r requirements.txt

      - name: Run tests
        working-directory: ci-pipeline-ml-model
        run: pytest -v

      #- name: Lint the code
      # working-directory: ci-pipeline-ml-model
      # run: .flake8