name: ML CI Test & Lint
on:
  push:
    paths:
      - 'ci-pipeline-ml-model/**'
  
  pull_request:
    paths:
      - 'ci-pipeline-ml-model/**'
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: pulling repo code into workflow environment
        uses: actions/checkout@v4
      
      - name: setup python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: installing dependencies
        working-directory: ci-pipeline-ml-model
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: pytest ci-pipeline-ml-model -v

      - name: Lint the code
        working-directory: ci-pipeline-ml-model
        run: flake8 src/ tests/